language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
branches:
  only:
    - master
    - develop
notifications:
  email:
    - muga.nishizawa@gmail.com
    - ozawa.tsuyoshi@gmail.com
    - leo@xerial.org
