language: scala
scala:
   - 2.11.1

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

branches:
  only:
    - master
    - develop
    - v07

script: sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  email:
    - muga.nishizawa@gmail.com
    - ozawa.tsuyoshi@gmail.com
    - leo@xerial.org
